### ISSUE TITLE
writestr() got an unexpected keyword argument 'compress_type'

### ISSUE THREAD

**Issue by watsonbox** [robweber/xbmcbackup#73]
Any idea what might be causing this issue? Thanks.

```
18:18:31 T:4641013760  NOTICE: script.xbmcbackup-1.0.2: Starting
18:18:31 T:4641013760  NOTICE: script.xbmcbackup-1.0.2: Local Dir: /Users/hwilson/Library/Application Support/Kodi/
18:18:31 T:4641013760  NOTICE: script.xbmcbackup-1.0.2: Remote Dir: 201505141818/
18:18:31 T:4641013760  NOTICE: script.xbmcbackup-1.0.2: Mode - Backup
18:18:31 T:4641013760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: writestr() got an unexpected keyword argument 'compress_type'
                                            Traceback (most recent call last):
                                              File "/Users/hwilson/Library/Application Support/Kodi/addons/script.xbmcbackup/default.py", line 69, in <module>
                                                backup.run(mode)
                                              File "/Users/hwilson/Library/Application Support/Kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 157, in run
                                                writeCheck = self._createValidationFile()
                                              File "/Users/hwilson/Library/Application Support/Kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 521, in _createValidationFile
                                                success = self.remote_vfs.put(xbmc.translatePath(utils.data_dir() + "xbmcbackup.val"),self.remote_vfs.root_path + "xbmcbackup.val")
                                              File "/Users/hwilson/Library/Application Support/Kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 100, in put
                                                self.zip.writestr(utils.encode(dest),aFile.read(),compress_type=zipfile.ZIP_DEFLATED)
                                            TypeError: writestr() got an unexpected keyword argument 'compress_type'
                                            -->End of Python script error report<--
```

**Comment by watsonbox** [comment]
Only seems to happen with 'Compress Archives' selected.

**Comment by robweber** [comment]
Going to guess this is an Android system? Kodi bundles an older version of python with Android that doesn't support that option when compressing archives. I've just pushed an update to the Kodi repo that addresses this for all builds of Kodi.

**Comment by watsonbox** [comment]
No, it's OSX Yosemite 10.10.3 running Kodi 14.2 Helix

**Comment by robweber** [comment]
I just looked and Android/IOS/and OSX all ship with the same (old) version of Python bundled with Kodi. Not sure why Windows and Linux are different but that's the way it works apparently. Look for version 1.0.5 of this addon to be in the repo soon, within a few days I'm hoping, and let me know if this issue resolves itself.

**Comment by watsonbox** [comment]
Sure, thanks a lot, will do.

**Comment by watsonbox** [comment]
Can confirm that this is now working fine in version 1.0.5.  Thanks for that.
